/**
 * Yoga & Dosha Engine — Type Definitions
 *
 * All shared types for the V1 yoga/dosha detection system.
 * Detectors return `YogaResult`, the orchestrator aggregates into `YogaAnalysisResponse`.
 */

import type { PlanetKey, PlanetData, AscendantData } from '@/types/astrology'

// ---------- Categories & natures ----------

export type YogaCategory =
  | 'mahapurusha'
  | 'raja'
  | 'dhana'
  | 'vipreet_raja'
  | 'moon'
  | 'marriage'
  | 'career'
  | 'general'
  | 'dosha'

export type YogaNature = 'positive' | 'challenging'

export type LifeArea =
  | 'career'
  | 'wealth'
  | 'marriage'
  | 'education'
  | 'children'
  | 'health'
  | 'family'
  | 'spirituality'
  | 'emotional_life'

// ---------- Strength / severity labels ----------

export type StrengthLabel =
  | 'weak'
  | 'moderate'
  | 'strong'
  | 'very_strong'
  | 'exceptional'

export type SeverityLabel =
  | 'mild'
  | 'moderate'
  | 'strong'
  | 'very_strong'

// ---------- Score breakdown ----------

export interface YogaScoreBreakdown {
  base: number
  planetStrength: number
  houseStrength: number
  dignity: number
  aspect: number
  relationship: number
  dasha: number
  afflictionPenalty: number
  cancellationPenalty: number
  final: number
}

export interface DoshaScoreBreakdown {
  base: number
  placementSeverity: number
  orbCloseness: number
  planetIntensity: number
  afflictionBoost: number
  lifeAreaImpact: number
  cancellationRelief: number
  final: number
}

// ---------- Detector result shapes ----------

export interface YogaResult {
  id: string
  name: string
  category: YogaCategory
  nature: YogaNature
  present: boolean
  score: number
  strength: StrengthLabel | null
  scoreBreakdown: YogaScoreBreakdown
  technicalReason: string
  planetsInvolved: PlanetKey[]
  housesInvolved: number[]
  lifeAreas: LifeArea[]
  currentlyActive: boolean
  /** Chart-specific narrative — "In your chart" prose generated by the detector */
  chartNarrative?: string
  /** Optional notes consumed by displayRules (e.g. "supersedes Sunapha+Anapha") */
  meta?: Record<string, unknown>
}

export interface DoshaResult {
  id: string
  name: string
  category: 'dosha'
  nature: 'challenging'
  present: boolean
  score: number
  severity: SeverityLabel | null
  scoreBreakdown: DoshaScoreBreakdown
  technicalReason: string
  planetsInvolved: PlanetKey[]
  housesInvolved: number[]
  lifeAreas: LifeArea[]
  currentlyActive: boolean
  /** Whether cancellation/relief factors meaningfully reduced severity */
  isReduced: boolean
  /** Chart-specific narrative — "In your chart" prose generated by the detector */
  chartNarrative?: string
  meta?: Record<string, unknown>
}

// ---------- Detector input ----------

/** Current dasha lords (optional — engine fetches if absent in API route) */
export interface CurrentDashaContext {
  mahadasha: PlanetKey | null
  antardasha: PlanetKey | null
  pratyantar: PlanetKey | null
}

export interface YogaEngineInput {
  /** All 9 planets keyed by name */
  planets: Record<string, PlanetData>
  /** Ascendant data */
  ascendant: AscendantData
  /** Current dasha periods (optional — disables dasha factor if missing) */
  currentDasha?: CurrentDashaContext
}

// ---------- Display tier output ----------

export interface YogaSummaryMetrics {
  positiveYogasFound: number
  challengingPatternsFound: number
  strongestYoga: string | null
  mostImportantCaution: string | null
  currentlyActive: string | null
}

export interface LifeAreaImpact {
  area: LifeArea
  /** -100 to +100 net score */
  netScore: number
  /** Display label */
  level: 'strong_support' | 'good_support' | 'moderate_support' | 'needs_effort' | 'challenging' | 'neutral'
  contributingYogas: string[]
}

export interface YogaDisplayCard {
  id: string
  name: string
  category: YogaCategory | 'dosha'
  nature: YogaNature
  score: number
  label: string
  shortMeaning: string
  /** Display priority — higher = ranked higher in UI */
  displayPriority: number
}

export interface YogaAnalysisResponse {
  /** Schema version — bump when shape changes */
  version: 1 | 2
  /** ISO timestamp */
  generatedAt: string
  summary: {
    text: string
    metrics: YogaSummaryMetrics
  }
  /** Top 3 sorted by displayPriority — already filtered for `present` */
  topPositive: YogaDisplayCard[]
  /** Top 2 sorted by displayPriority — already filtered for `present` */
  topChallenging: YogaDisplayCard[]
  /** All detected yogas (excludes not-present) */
  allYogas: YogaResult[]
  /** All detected doshas (excludes not-present) */
  allDoshas: DoshaResult[]
  /** Aggregated life-area impact across all detected items */
  lifeAreas: LifeAreaImpact[]
  /** Empty-state message when no yogas detected */
  emptyYogasMessage: string | null
  /** Empty-state message when no doshas detected */
  emptyDoshasMessage: string | null
}
